/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as StreaksIndexRouteImport } from './routes/streaks/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as UsersUsernameRouteImport } from './routes/users/$username'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos/$owner.$repo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreaksIndexRoute = StreaksIndexRouteImport.update({
  id: '/streaks/',
  path: '/streaks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/repos/$owner/$repo',
  path: '/repos/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users/$username': typeof UsersUsernameRoute
  '/repos/': typeof ReposIndexRoute
  '/streaks/': typeof StreaksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users/$username': typeof UsersUsernameRoute
  '/repos': typeof ReposIndexRoute
  '/streaks': typeof StreaksIndexRoute
  '/users': typeof UsersIndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users/$username': typeof UsersUsernameRoute
  '/repos/': typeof ReposIndexRoute
  '/streaks/': typeof StreaksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users/$username'
    | '/repos/'
    | '/streaks/'
    | '/users/'
    | '/repos/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users/$username'
    | '/repos'
    | '/streaks'
    | '/users'
    | '/repos/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/users/$username'
    | '/repos/'
    | '/streaks/'
    | '/users/'
    | '/repos/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UsersUsernameRoute: typeof UsersUsernameRoute
  ReposIndexRoute: typeof ReposIndexRoute
  StreaksIndexRoute: typeof StreaksIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaks/': {
      id: '/streaks/'
      path: '/streaks'
      fullPath: '/streaks/'
      preLoaderRoute: typeof StreaksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username': {
      id: '/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UsersUsernameRoute: UsersUsernameRoute,
  ReposIndexRoute: ReposIndexRoute,
  StreaksIndexRoute: StreaksIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
